### ISSUE TITLE
Fatalerror in admin/go2.php

### ISSUE THREAD

**Issue by xoopsfan** [XoopsModules25x/mastop_go2#4]
Im Testing this on wamp

Mastop Go2 1.02 Final
XOOPS Version	XOOPS 2.5.9-RC1
PHP Version	5.6.25
mySQL Version	5.7.14

in admin i received fatal error for this page 
modules/mastop_go2/admin/go2.php
Fatal error: Call to undefined method MastopFormSelectImage::XoopsFormSelect() in D:\wamp\www\xoops\modules\mastop_go2\class\formimage.php on line 38

**Comment by mambax7** [comment]
You can check out this version if it works:
https://github.com/mambax7/mastop_go2

**Comment by mambax7** [comment]
Check 1.04 RC1 in https://github.com/XoopsModules25x/mastop_go2/releases
